// Generated by CoffeeScript 1.7.1
var ChartView, d3, util,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

util = require('../../helpers/graph-util.coffee');

d3 = require('d3');

ChartView = (function(_super) {
  __extends(ChartView, _super);

  function ChartView() {
    return ChartView.__super__.constructor.apply(this, arguments);
  }

  ChartView.prototype.template = require('./chart-view.jade');

  ChartView.prototype.model = "BillModel";

  ChartView.prototype.initialize = function() {};

  ChartView.prototype.render = function() {
    var formatDate;
    return formatDate = d3.time.format.iso;
  };

  return ChartView;

})(Marionette.ItemView);

module.exports = ChartView;
