// Generated by CoffeeScript 1.7.1
var EnactedtView, util, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = window._;

util = require('../../helpers/graph-util.coffee');

EnactedtView = (function(_super) {
  __extends(EnactedtView, _super);

  function EnactedtView() {
    return EnactedtView.__super__.constructor.apply(this, arguments);
  }

  EnactedtView.prototype.template = require('./enacted-view.jade');

  EnactedtView.prototype.model = "EnactedModel";

  EnactedtView.prototype.tagName = "svg";

  EnactedtView.prototype.events = {
    'mouseover [data-amdt]': 'showAmendmentData'
  };

  EnactedtView.prototype.initialize = function() {};

  EnactedtView.defaults = function() {
    var margin;
    return margin = {
      top: 30,
      right: 10,
      bottom: 10,
      left: 10
    };
  };

  EnactedtView.prototype.render = function() {
    var height, margin, parseDate, width;
    parseDate = d3.time.format("%Y-%m-%dT%H:%M:%SZ").parse;
    margin = {
      top: 30,
      right: 10,
      bottom: 10,
      left: 10
    };
    width = $("#chart").width() - margin.right - margin.left;
    return height = data.length * 12;
  };

  return EnactedtView;

})(Marionette.ItemView);

module.exports = EnactedView;
