// Generated by CoffeeScript 1.7.1
var EnactedtView, bubbles, data, util, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_ = window._;

util = require('../../helpers/graph-util.coffee');

data = require('./../../../../assets/data/enacted.json');

bubbles = require('./../../helpers/bubble-chart.coffee');

EnactedtView = (function(_super) {
  __extends(EnactedtView, _super);

  function EnactedtView() {
    return EnactedtView.__super__.constructor.apply(this, arguments);
  }

  EnactedtView.prototype.template = require('./enacted-view.jade');

  EnactedtView.prototype.model = "EnactedModel";

  EnactedtView.prototype.tagName = "svg";

  EnactedtView.prototype.initialize = function() {};

  EnactedtView.defaults = function() {
    var margin;
    return margin = {
      top: 30,
      right: 10,
      bottom: 10,
      left: 10
    };
  };

  EnactedtView.prototype.render = function() {
    this.data = data;
    return $(function() {
      var chart, render_vis;
      chart = null;
      render_vis = function(json) {
        chart = new BubbleChart(json);
        chart.start();
        return root.display_all();
      };
      root.display_all = (function(_this) {
        return function() {
          return chart.display_group_all();
        };
      })(this);
      root.display_year = (function(_this) {
        return function() {
          return chart.display_by_year();
        };
      })(this);
      root.toggle_view = (function(_this) {
        return function(view_type) {
          if (view_type === 'year') {
            return root.display_year();
          } else {
            return root.display_all();
          }
        };
      })(this);
      return d3.json(this.data, render_vis);
    });
  };

  return EnactedtView;

})(Marionette.ItemView);

module.exports = EnactedView;
