// Generated by CoffeeScript 1.7.1
var BillModel,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BillModel = (function(_super) {
  __extends(BillModel, _super);

  function BillModel() {
    return BillModel.__super__.constructor.apply(this, arguments);
  }

  BillModel.prototype.urlRoot = 'http://omnibus-backend.azurewebsites.net/api/bills/';

  BillModel.prototype.initialize = function(id) {
    return this.id = id;
  };

  BillModel.prototype.then = function(callback) {
    this._when.then(callback);
    return this;
  };

  BillModel.prototype.getAmendments = function() {
    return $.ajax("/api/bills/" + this.id + "/amendments").then((function(_this) {
      return function(data) {
        return _this.amendments = new Amendments(data.results);
      };
    })(this));
  };

  BillModel.prototype.getVotes = function() {
    return $.ajax("/api/bills/" + this.id + "/votes").then((function(_this) {
      return function(data) {
        return _this.votes = new Votes(data.results);
      };
    })(this));
  };

  BillModel.prototype.parse = function(response) {
    var data;
    data = {};
    return data.results = JSON.parse(response);
  };

  return BillModel;

})(Backbone.Model);

module.exports = BillModel;
