// Generated by CoffeeScript 1.7.1
var VoteModel,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

VoteModel = (function(_super) {
  __extends(VoteModel, _super);

  function VoteModel() {
    return VoteModel.__super__.constructor.apply(this, arguments);
  }

  VoteModel.prototype.initialize = function(options) {
    return this.url = 'http://omnibus-backend.azurewebsites.net/api/votes/bill' + options.id + '/votes';
  };

  VoteModel.prototype.urlRoot = VoteModel.url;

  VoteModel.prototype.parse = function(response) {
    var data;
    data = {};
    data.results = JSON.parse(response);
    return console.log(data.results);
  };

  return VoteModel;

})(Backbone.Model);

module.exports = VoteModel;
