// Generated by CoffeeScript 1.7.1
(function() {
  var App, expect, should;

  App = require('./app');

  expect = chai.expect;

  should = chai.should();

  App.start();

  module.exports = describe('app:', function() {
    return describe('regions', function() {
      return it('should exist', function() {
        should.exist(App.search);
        should.exist(App.chart);
        return should.exist(App.sideData);
      });
    });
  });

}).call(this);
