// Generated by CoffeeScript 1.7.1
var App, MainController, currentCongress, firstBill, firstBillId;

MainController = require('./controller.coffee');

App = new Backbone.Marionette.Application();


BillModel = require('./models/bill-model.coffee');
currentCongress = 113;

firstBill = 'hr2397';

firstBillId = currentCongress + '-' + firstBill;

App.addRegions({
  welcome: '#welcome',
  search: '#search',
  content: '#content'
});

App.on('before:start', function(options) {
  this.controller = new MainController({
    regions: {
      welcome: this.welcome,
      search: this.search,
      content: this.content
    }
  });
  return this.router = new Marionette.AppRouter({
    controller: this.controller,
    appRoutes: {
      '': 'home',
      'bill/:id': 'showBill'
    }
  });
});

App.on('start', function(options) {
  if (Backbone.history) {
    return Backbone.history.start({
      pushState: true
    });
  }
});

window.App = App;

module.exports = App;
