// Generated by CoffeeScript 1.7.1
var App, MainController;

MainController = require('./controller.coffee');

App = new Backbone.Marionette.Application();

App.addRegions({
  welcome: '#welcome',
  search: '#search',
  content: '#content'
});

App.spinnerOptions = {
  radius: 30,
  lines: 22,
  length: 16,
  speed: .75
};

App.spinner = new Spinner(this.spinnerOptions).spin();

App.on('before:start', function(options) {
  this.controller = new MainController({
    regions: {
      welcome: this.welcome,
      search: this.search,
      content: this.content
    }
  });
  this.router = new Marionette.AppRouter({
    controller: this.controller,
    appRoutes: {
      '': 'home',
      'bills/:id': 'showBill',
      'bills/search/:query': 'searchResults'
    }
  });
  return this.controller.router = this.router;
});

App.on('start', function(options) {
  if (Backbone.history) {
    return Backbone.history.start({
      pushState: true
    });
  }
});

window.App = App;

module.exports = App;
