// Generated by CoffeeScript 1.7.1
(function() {
  var MainRouter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MainRouter = (function(_super) {
    __extends(MainRouter, _super);

    function MainRouter() {
      return MainRouter.__super__.constructor.apply(this, arguments);
    }

    MainRouter.routes = {
      '': 'home'
    };

    MainRouter.home = function() {
      return MainRouter.navigate('someRoute', {
        trigger: true,
        replace: true
      });
    };

    return MainRouter;

  })(Marionette.AppRouter);

  module.exports = MainRouter;

}).call(this);
