// Generated by CoffeeScript 1.7.1
var WelcomeView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

WelcomeView = (function(_super) {
  __extends(WelcomeView, _super);

  function WelcomeView() {
    return WelcomeView.__super__.constructor.apply(this, arguments);
  }

  WelcomeView.prototype.template = require('./welcome-view.jade', {
    events: {
      'click .hide-button': 'hide'
    },
    hide: function() {
      return window.App.vent.trigger('hide');
    }
  });

  return WelcomeView;

})(Marionette.ItemView);

module.exports = WelcomeView;
